import { useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { ArrowRight, Check, CheckCheck, Copy, LockKeyhole, ShieldCheck, Sparkles, Users } from 'lucide-react';
import { QRCodeSVG } from 'qrcode.react';
import { Button, Empty, ErrorNotice, LinkButton, Loading, PageHeading, PrivateNote, StayArt, Tag } from './components';
import { post, segment } from './api';
import { useAction, useResource } from './hooks';

export function Landing() {
  return <div className="landing"><section className="hero"><div className="hero-copy"><p className="eyebrow"><span className="tiny-star">✳</span> Find your common ground</p><h1>Plan together.<br />Pay together.<br /><em>Keep your boundaries private.</em></h1><p className="hero-tagline">Good plans make room for everyone.</p><p className="hero-description">Accord privately understands what works for everyone, finds a shared option, and makes sure the group only purchases the exact offer everyone approved.</p><div className="hero-actions"><LinkButton to="/rooms/new">Create a group</LinkButton><LinkButton to="/join" secondary>Join a group</LinkButton></div><p className="hero-footnote"><LockKeyhole size={14} /> Your limits don’t need an explanation.</p></div><div className="hero-visual"><div className="visual-heading"><span>THE NEXT CHAPTER</span><span>TOGETHER, ON YOUR TERMS ↗</span></div><StayArt city="Miami" large /><div className="floating-note note-private"><span className="icon-circle"><LockKeyhole size={18} /></span><div><strong>A space for your boundaries</strong><span>Only you and Accord.</span></div></div><div className="agreement-card"><div className="avatar-flow" aria-hidden="true"><span>A</span><span>P</span><span>J</span><span>M</span><i /><span className="agreement-check"><Check size={20} /></span></div><div><strong>Four people. One common ground.</strong><p>Everyone gets a say. Everyone stays themselves.</p></div><span className="illustrative">An illustration of agreement</span></div></div></section><section id="how-it-works" className="how-section"><div><p className="eyebrow">Less back-and-forth. More looking forward.</p><h2>Good together.<br /><em>Right for each of you.</em></h2></div><div className="how-grid">{[{ icon: LockKeyhole, n: '01', title: 'Tell Accord privately', text: 'Your budget, your needs, your non-negotiables. Share what matters, without explaining why.' }, { icon: Sparkles, n: '02', title: 'Find the shared yes', text: 'Accord checks the options against everyone’s confirmed requirements. Your group sees the possibilities.' }, { icon: ShieldCheck, n: '03', title: 'Approve the exact plan', text: 'Everyone authorizes their own share. If the offer changes, your old approval stays with the old offer.' }].map(item => <article key={item.n}><div className="between"><item.icon size={23} strokeWidth={1.5} /><span>{item.n}</span></div><h3>{item.title}</h3><p>{item.text}</p></article>)}</div></section><section className="closing-note"><span className="tiny-star">✳</span><p>A great trip starts with a plan<br /><em>everyone can feel good about.</em></p><Link to="/rooms/new" className="text-button">Let’s bring it together <ArrowRight size={18} /></Link></section></div>;
}

type CreatedRoom = { roomId: string; inviteToken: string };
export function NewRoom() {
  const [created, setCreated] = useState<CreatedRoom>();
  const action = useAction();
  const [copied, setCopied] = useState(false);
  const invite = created ? `${window.location.origin}/join/${segment(created.inviteToken)}` : '';
  return <div className="page narrow"><PageHeading eyebrow="A little planning, a lot of possibility" title={created ? 'Make room for everyone.' : 'Bring your people together.'} description={created ? 'Share this invitation. Each friend joins with their own private session.' : 'Start with a shared goal. Everyone’s personal boundaries come next, privately.'} />{created ? <section className="panel invite-panel"><Tag><Users size={14} />Your group is ready for company</Tag><div className="qr"><QRCodeSVG value={invite} size={164} level="M" title="Scan to join this Accord group" /></div><label htmlFor="invite-link">Your invite link</label><div className="copy-field"><input id="invite-link" readOnly value={invite} /><Button className="secondary" onClick={() => action.run(async () => { await navigator.clipboard.writeText(invite); setCopied(true); })}>{copied ? <Check size={17} /> : <Copy size={17} />}<span>{copied ? 'Copied' : 'Copy'}</span></Button></div><PrivateNote /><LinkButton to={`/rooms/${segment(created.roomId)}`}>Go to your waiting room</LinkButton><Link className="text-button" to={`/rooms/${segment(created.roomId)}/me/intake`}>Set your private requirements <ArrowRight size={16} /></Link></section> : <form className="panel form-panel" onSubmit={event => { event.preventDefault(); const data = new FormData(event.currentTarget); action.run(async () => setCreated(await post<CreatedRoom>('/rooms', { name: data.get('name'), goal: data.get('goal'), displayName: data.get('displayName') }))); }}><label htmlFor="room-name">Give your group a name</label><input id="room-name" name="name" maxLength={100} required defaultValue="Spring Break Stay" /><label htmlFor="goal">What are you planning together?</label><textarea id="goal" name="goal" required maxLength={500} defaultValue="Book a shared four-night stay for four friends." rows={3} /><label htmlFor="host-name">Your display name</label><input id="host-name" name="displayName" required maxLength={60} autoComplete="given-name" placeholder="What should your friends call you?" /><PrivateNote /><Button disabled={action.busy}>{action.busy ? 'Creating your group…' : 'Create a group'}<ArrowRight size={17} /></Button><p className="fine">Creating a group doesn’t authorize any payment.</p></form>}<ErrorNotice error={action.error} /></div>;
}

export function JoinEntry() {
  const navigate = useNavigate();
  const [error, setError] = useState<Error>();
  return <div className="page narrow"><PageHeading eyebrow="There’s a place for you" title="Meet your group here." description="Paste the invitation your friend shared with you." /><form className="panel form-panel" onSubmit={event => { event.preventDefault(); setError(undefined); const value = String(new FormData(event.currentTarget).get('invite')).trim(); try { const url = new URL(value, window.location.origin); if (url.origin !== window.location.origin || !/^\/join\/[^/]+\/?$/.test(url.pathname)) throw new Error(); navigate(url.pathname); } catch { setError(new Error('Enter a full Accord invite link from this site.')); } }}><label htmlFor="invite">Invitation link</label><input id="invite" name="invite" type="text" required placeholder={`${window.location.origin}/join/…`} /><Button>Find my group <ArrowRight size={17} /></Button><PrivateNote /></form><ErrorNotice error={error} /></div>;
}

export function JoinRoom() {
  const { inviteToken = '' } = useParams();
  const resource = useResource<{ name: string; goal: string; memberCount: number }>(`/invites/${segment(inviteToken)}`);
  const navigate = useNavigate();
  const action = useAction();
  return <div className="page narrow"><PageHeading eyebrow="An invitation to find common ground" title="Your people are planning something." />{resource.loading && <Loading />}<ErrorNotice error={resource.error} retry={resource.refresh} />{resource.data && <form className="panel form-panel" onSubmit={event => { event.preventDefault(); const displayName = new FormData(event.currentTarget).get('displayName'); action.run(async () => { const result = await post<{ roomId: string }>(`/invites/${segment(inviteToken)}/join`, { displayName }); navigate(`/rooms/${segment(result.roomId)}/me/intake`); }); }}><Tag><Users size={14} />{resource.data.memberCount} joined</Tag><h2>{resource.data.name}</h2><p className="subtle">{resource.data.goal}</p><label htmlFor="display-name">Your display name</label><input id="display-name" name="displayName" required maxLength={60} autoComplete="given-name" placeholder="What should we call you?" /><PrivateNote /><Button disabled={action.busy}>{action.busy ? 'Joining securely…' : 'Join privately'}<LockKeyhole size={16} /></Button><p className="fine">You’ll review your own requirements and approve your own contribution.</p></form>}<ErrorNotice error={action.error} /></div>;
}
